### ISSUE TITLE
Turn on regro-cf-autotick-bot

### ISSUE THREAD

**Issue by sgillies** [conda-forge/planet-feedstock#35]
https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch

cc @jreiberkyle

**Comment by sgillies** [comment]
Ah, from https://github.com/conda-forge/planet-feedstock/pull/30 I see it's already set up.

@ocefpaf do any changes need to be made to https://github.com/regro-cf-autotick-bot/planet-feedstock in order to get automated dev build PRs?

**Comment by ocefpaf** [comment]
> @ocefpaf do any changes need to be made to https://github.com/regro-cf-autotick-bot/planet-feedstock in order to get automated dev build PRs?

I don't think we ever implement automated dev builds. @beckermr can correct me if I'm misremembering.

**Comment by sgillies** [comment]
@ocefpaf I think that's fine. It's probably better to keep dev builds manual, it creates an incentive to wrap up it up and have a stable release :stuck_out_tongue_winking_eye:
